name: Docker Compose Test

on:
  push:
    branches: [ main ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: |
          # Wait for the test container to complete
          timeout=300  # 5 minutes
          start_time=$(date +%s)
          
          while true; do
            # Check if test container is still running
            if ! docker ps | grep -q spark-connect-proxy-test-1; then
              echo "Test container has finished running"
              break
            fi
            
            # Check timeout
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            if [ $elapsed -ge $timeout ]; then
              echo "Timeout waiting for test container to complete"
              exit 1
            fi
            
            echo "Waiting for test container to complete... ($elapsed seconds elapsed)"
            sleep 5
          done

      - name: Check test container exit code
        run: |
          # Get the exit code of the test container
          exit_code=$(docker inspect --format='{{.State.ExitCode}}' spark-connect-proxy-test-1)
          
          if [ "$exit_code" -eq 0 ]; then
            echo "Test container exited successfully with code 0"
          else
            echo "Test container failed with exit code $exit_code"
            # Print logs from the test container
            docker logs spark-connect-proxy-test-1
            exit 1
          fi

      - name: Show logs from all services
        if: ${{ always() }}
        run: docker-compose logs

      - name: Clean up
        if: ${{ always() }}
        run: docker-compose down -v